name: checks
on:
  - push
  - pull_request

jobs:
  test:
    uses: japa/browser-client/.github/workflows/test.yml@next
    with:
      install-playwright-browsers: true

  lint:
    uses: japa/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: japa/.github/.github/workflows/typecheck.yml@main
